GET http://127.0.0.1:5000/msgs/

###

POST http://127.0.0.1:5000/msgs
Content-Type: application/json

{
  "textMsg": "Hey, Julia! What’s up?",
  "email": "erato@gmail.com",
  "timeDate": "{{$datetime rfc1123}}"
}

###

PATCH  http://127.0.0.1:5000/msgs/1
Content-Type: application/json

{
  "textMsg": "Hello there, Sam, not much. How are you doing? I’ve heard you bought yourself a new car!",
  "email": "erato1@gmail.com",
  "timeDate": "{{$datetime rfc1123}}"
}

###

DELETE http://127.0.0.1:5000/msgs/e72b1d37-2496-4caf-90ef-0cc01e1543f3